[ted]
title = "TED Talks 한국어"
url = "https://www.ted.com/talks?sort=newest&language=ko"
entrySelector = "div[class='row row-sm-4up row-lg-6up row-skinny'] div[class='col']"
titleSelector = "h4[class='f-w:700 h9 m5']"
linkSelector = "h4[class='f-w:700 h9 m5'] a"
contentSelector = "h4.h12.talk-link__speaker"
waitUntil = "networkidle"

[dotface]
title = "닷페이스 ─ 아티클"
url = "https://articles.dotface.kr/"
entrySelector = "div.css-1oskuwq div.css-1pnb0mm-Item"
titleSelector = "div.css-1jg502e"
linkSelector = "a.css-yvles8-MainSection"
contentSelector = "div.css-jc8v6j"
waitUntil = "networkidle"

[kakaotv_eanakim]
title = "kakaoTV ─ 톡이나 할까"
url = "https://tv.kakao.com/channel/3647846/video"
entrySelector = "ul.list_vertical li"
titleSelector = "strong.tit_item"
linkSelector = "a.link_contents"
contentSelector = "span.mark_play"
imageSelector = "span.thumb_box img.thumb_img"
waitUntil = "networkidle"

[parkjy0217]
title = "동아사이언스 ─ 박진영 심리학 칼럼니스트"
url = "https://www.dongascience.com/journalist.php?email=parkjy0217%40gmail.com"
entrySelector = "div.article-A2 ul li"
titleSelector = "dd span.tit"
linkSelector = "a"
contentSelector = "span.cont"
waitUntil = "networkidle"

[parkjy_naver]
title = "동아사이언스 박진영 심리학 칼럼니스트 ─ 네이버 뉴스"
url = "https://news.naver.com/main/hotissue/sectionList.naver?mid=hot&sid1=110&cid=1077376"
entrySelector = "ul.tmp_bx li.tmp.small2"
titleSelector = "dl.cnt dt.t a"
linkSelector = "dl > dt > a"
contentSelector = "dd.c"
imageSelector = "div.thumb a img"
waitUntil = "networkidle"

[factcheck_naver]
title = "SNU 팩트체크 ─ 네이버 뉴스"
url = "https://m.news.naver.com/factcheck/main"
entrySelector = "div.factcheck_list div.factcheck_item._factcheck_item"
titleSelector = "p[class='factcheck_subject_summary']"
linkSelector = "p[class='factcheck_subject_summary'] a"
contentSelector = "div[class^='factcheck_source_rating is']"
waitUntil = "networkidle"

[hyunddaily]
title = "디지털데일리 박현영 기자 ─ 네이버 뉴스"
url = "https://media.naver.com/journalist/138/74334"
entrySelector = "ul.press_edit_news_list li.press_edit_news_item.as_thumb"
titleSelector = "span.press_edit_news_title"
linkSelector = "a.press_edit_news_link"
contentSelector = "span.r_ico_b.r_modify"
imageSelector = "span.press_edit_news_thumb img"
waitUntil = "networkidle"
