[musinsa]
title = "무신사 ─ 패션 뉴스"
url = "https://magazine.musinsa.com/?m=news"
entrySelector = "ul[class='news-article-list article-list list'] li[class='listItem']"
titleSelector = "p[class='title'] a"
linkSelector = "div.articleImg > a"
imageSelector = "div[class='articleImg'] a img"
contentSelector = "div[class='description'] a p"

[musinsa_recruit]
title = "무신사 ─ 구인"
url = "https://magazine.musinsa.com/?m=recruit"
entrySelector = "ul[class='recruit-article-list article-list list'] li"
titleSelector = "ul li a[class='title']"
linkSelector = "ul li a[class='title']"
imageSelector = "a.img > img"
contentSelector = "p[class='job']"
