[parkjy0217]
title = "동아사이언스 ─ 박진영 심리학 칼럼니스트"
url = "https://www.dongascience.com/journalist.php?email=parkjy0217%40gmail.com"
entrySelector = "div.article-A2 ul li"
titleSelector = "dd span.tit"
linkSelector = "a"
contentSelector = "span.cont"
waitUntil = "networkidle"

[parkjy_naver]
title = "동아사이언스 박진영 심리학 칼럼니스트 ─ 네이버 뉴스"
url = "https://news.naver.com/main/hotissue/sectionList.naver?mid=hot&sid1=110&cid=1077376"
entrySelector = "ul.tmp_bx li.tmp.small2"
titleSelector = "dl.cnt dt.t a"
linkSelector = "dl > dt > a"
contentSelector = "dd.c"
imageSelector = "div.thumb a img"

[hyunddaily]
title = "디지털데일리 박현영 기자 ─ 네이버 뉴스"
url = "https://media.naver.com/journalist/138/74334"
entrySelector = "ul.press_edit_news_list li.press_edit_news_item.as_thumb"
titleSelector = "span.press_edit_news_title"
linkSelector = "a.press_edit_news_link"
contentSelector = "span.r_ico_b.r_modify"
imageSelector = "span.press_edit_news_thumb img"
