[musinsa_news]
title = "무신사 ─ 패션 뉴스"
url = "https://magazine.musinsa.com/?m=news"
entrySelector = "ul[class='news-article-list article-list list'] li[class='listItem']"
titleSelector = "p[class='title'] a"
linkSelector = "div.articleImg > a"
imageSelector = "div[class='articleImg'] a img"
contentSelector = "div[class='description'] a p"

[musinsa_recruit]
title = "무신사 ─ 구인"
url = "https://magazine.musinsa.com/?m=recruit"
entrySelector = "ul[class='recruit-article-list article-list list'] li"
titleSelector = "a.title"
linkSelector = "a[class='title']"
contentSelector = "p[class='job']"

[musinsa_magazine]
title = "무신사 ─ 매거진"
url = "https://magazine.musinsa.com/?m=magazine"
entrySelector = "ul[class='magazine-article-list article-list list'] li[class='listItem']"
titleSelector = "div.title"
linkSelector = "div[class='articleImg'] a"
contentSelector = "p[class='description']:not(.mediumName)"
imageSelector = "img.lazy-load-image"

[naverpost_musinsa_snap]
title = "무신사 ─ 무신사 스냅"
url = "https://post.naver.com/my/series/detail.naver?seriesNo=195255&memberNo=22191262"
entrySelector = "#el_list_container ul ul li"
titleSelector = "div.spot_post_name span.ell"
linkSelector = "a[href]"
imageSelector = "img"
contentSelector = "span.writer_name"

[naverpost_musinsa_report]
title = "무신사 ─ 무신사 리포트"
url = "https://post.naver.com/my/series/detail.naver?seriesNo=508128&memberNo=22191262"
entrySelector = "#el_list_container ul ul li"
titleSelector = "div.spot_post_name span.ell"
linkSelector = "a[href]"
imageSelector = "img"
contentSelector = "span.writer_name"

[naverpost_musinsa_stylefactory]
title = "무신사 ─ 스타일 팩토리"
url = "https://post.naver.com/my/series/detail.naver?seriesNo=369379&memberNo=22191262"
entrySelector = "#el_list_container ul ul li"
titleSelector = "div.spot_post_name span.ell"
linkSelector = "a[href]"
imageSelector = "img"
contentSelector = "span.writer_name"

[naverpost_musinsa_stylelesson]
title = "무신사 ─ 스타일 레슨"
url = "https://post.naver.com/my/series/detail.naver?seriesNo=225468&memberNo=22191262"
entrySelector = "#el_list_container ul ul li"
titleSelector = "div.spot_post_name span.ell"
linkSelector = "a[href]"
imageSelector = "img"
contentSelector = "span.writer_name"

[naverpost_musinsa_storerank]
title = "무신사 ─ 무신사 스토어 랭킹"
url = "https://post.naver.com/my/series/detail.naver?seriesNo=195260&memberNo=22191262"
entrySelector = "#el_list_container ul ul li"
titleSelector = "div.spot_post_name span.ell"
linkSelector = "a[href]"
imageSelector = "img"
contentSelector = "span.writer_name"
