[musinsa]
title = "무신사 ─ 패션 뉴스"
url = "https://magazine.musinsa.com/?m=news"
entrySelector = "ul[class='news-article-list article-list list'] li[class='listItem']"
titleSelector = "p[class='title'] a"
linkSelector = "div.articleImg > a"
imageSelector = "div[class='articleImg'] a img"
contentSelector = "div[class='description'] a p"